//
// Generated file, do not edit! Created by nedtool 5.6 from aoid.msg.
//

#ifndef __AOID_M_H
#define __AOID_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class AoId;
/**
 * Class generated from <tt>aoid.msg:15</tt> by nedtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet AoId
 * {
 *     int which;
 * }
 * </pre>
 */
class AoId : public ::omnetpp::cPacket
{
  protected:
    int which = 0;

  private:
    void copy(const AoId& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AoId&);

  public:
    AoId(const char *name=nullptr, short kind=0);
    AoId(const AoId& other);
    virtual ~AoId();
    AoId& operator=(const AoId& other);
    virtual AoId *dup() const override {return new AoId(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getWhich() const;
    virtual void setWhich(int which);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AoId& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AoId& obj) {obj.parsimUnpack(b);}

#endif // ifndef __AOID_M_H

